### ISSUE TITLE
Support For Android

### ISSUE THREAD

**Issue by Nzzyme** [HalieStamm9/google-unlocked#35]
Can you please add support for Chrome / Firefox for Android? I use the AdGuard app which supports 'Extensions'. I tried adding this script in AG but I did not see the script working in Chrome for Android.

**Comment by DineshSolanki** [comment]
you can use firefox nightly for android, and use the extension in that.

**Comment by Nzzyme** [comment]
> you can use firefox nightly for android, and use the extension in that.

Thanks. I'll check it out

**Comment by Duckdu12** [comment]
I cant add extension in firefox nightly

**Comment by DineshSolanki** [comment]
> I cant add extension in firefox
 take a look here - https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

https://www.reddit.com/r/firefox/comments/j1ta1s/you_can_now_add_any_addon_in_firefox_nightly/?utm_source=share&utm_medium=web2x&context=3

**Comment by Ibit-to** [comment]
seems to be reolved

**Comment by Nzzyme** [comment]
> you can use firefox nightly for android, and use the extension in that.

https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android
