### ISSUE TITLE
Extention doesnt work

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [HalieStamm9/google-unlocked#36]
i tried to use the extension with ibit.to to check it if would work, the extension does nothing more than normal google however the user script works perfectly.

**Comment by Ibit-to** [comment]
You need to do a search on google.com

**Comment by TWIISTED-STUDIOS** [comment]
that is precisely what i did, i used your suggestion ofseraching ibit.to with the extension installed, it was just a basic google search with no extra searches at the bottom, I then tried with the user script and that worked straight away, just thought I would let you know of my findings.
